### PR TITLE
prep_for_vasp.ipynb

### PR DESCRIPTION
**Pull request by lukeamyers**
added the prep_for_vasp.ipynb. This takes the YWoutput from ATAT, removes the spin up less than spin down configs, and organizes all the unique configurations so that they are ready to run in vasp.

### CODE REVIEW

**Comment by nhew1994** [comment]
# Then convert CIF to POSCAR using ASE
atoms = io.read(tmp)
atoms.write(structure_to, format='vasp')

Does this preserve the order of the atoms? (same order as str.out). 

Is there any difference if you use:
# Create the POSCAR file
        # Convert str.out to CIF format first
        tmp = 'tmp.cif'
        cmd = f'str2cif < str.out > tmp.cif'
        os.system(cmd)

        # Then convert CIF to POSCAR
        parser = CifParser(tmp)
        structure = parser.parse_structures()[0]
        poscar = Poscar(structure)
        poscar.write_file("POSCAR")

**Comment by lukeamyers** [comment]
Yes, ASE preserves the site order. however, using pymatgen would be more consistent, and we won't need to import ASE. I'll make the necessary changes.

**Comment by lukeamyers** [comment]
It seems using CifParser, doesn't maintain site order if in the CIF the sites are not grouped by atom. I do need to solve this problem though, so we can merge that into main when it's done. For now I've made another branch from dev/luke called no_ase, that is starting to do this.

**Comment by lukeamyers** [comment]
Running the function rearrange_sites_and_magmoms() for each config will patch the issue of sites not being grouped by magmom. it's not the ideal way to do it; this way basically writes the poscar and incar incorrectly, but then running the new function fixes it. it works though, which is what I need rn.

**Pull request merged**
