### PR TITLE
small changes

### PR DESCRIPTION
**Pull request by lukeamyers**
- Added option color_assignment in plot_conifig_energy() for custom colors
- Default color scheme is plotly
- added TODO remove "config" from displaying in the legened of plot_ev figures
- reformatted plot_config_energy() header

### CODE REVIEW

**Comment by nhew1994** [comment]
TODO: highlight the actual minimum from the fitting should still be there. At the moment it looks like the min on the plot is taken from the min of the curve points not the actual min from the fitting, but it is a very small difference.

**Comment by lukeamyers** [comment]
No it's the min of the fitted curve

r2scan_ev_curves_edit3

**Comment by nhew1994** [comment]
Yes, but its not the actual eos parameters from the fitting: 
if highlight_minimum == True:
                    min_energy = min(eos_name_df["energies"].values[0])
                    volume_at_min_energy = eos_name_df["volumes"].values[0][
                        np.where(eos_name_df["energies"].values[0] == min_energy)[0][0]
                    ]

Should be V0 and E0 from fit_to_all_eos. But there is only a very small difference if you plot enough points.

**Comment by lukeamyers** [comment]
mmm I understand

**Review by nhew1994 — APPROVED** [review]

**Pull request merged**
