### PR TITLE
Dev/luke

### PR DESCRIPTION
**Pull request by lukeamyers**
Changes to eos_fit.plot_ev and plot_energy_difference.

Formatting is improved

image

### CODE REVIEW

**Comment by lukeamyers** [comment]
I need to make text larger

**Comment by lukeamyers** [comment]
I should also consider better placement of legend

**Comment by lukeamyers** [comment]
Changed text. looks like there is no easy way to programmatically place the legend inside the plot, in a good location. So keeping it on the right outside looks best I think.

image

**Comment by nhew1994** [comment]
Looks very nice. I think you can:
1) Increase the font of the x and y tick marks and change the color to black. It looks grey?
2) Can you remove italics for the axis labels? 
3) If you have axis labels you can remove the title 
4) Remove BM4 fit 
5) Does the legend not automatically place itself?

Thanks.

**Comment by lukeamyers** [comment]
> Looks very nice. I think you can:
> 
>     1. Increase the font of the x and y tick marks and change the color to black. It looks grey?
> 
>     2. Can you remove italics for the axis labels?
> 
>     3. If you have axis labels you can remove the title
> 
>     4. Remove BM4 fit
> 
>     5. Does the legend not automatically place itself?
> 
> 
> Thanks.

Good suggestions

1. Done.
2. Done.
3. Done. However, I think I will actually add a parameter in the function to title with the material name or something if one wants.
4. Done.
5. It does. I was just thinking the image would shape better if the legened was inside the plot, but there is no good way to automatically do that in plotly. So the default is outside. one could manualy edit the figure with plotly if they wish to place it arbitrarily.

**Comment by nhew1994** [comment]
Great, thanks.

**Pull request merged**
