### PR TITLE
ENH: Modified the debye module dataframe to handle multiple configurations

### PR DESCRIPTION
**Pull request by nhew1994**

### CODE REVIEW

**Review by lukeamyers — APPROVED** [review]
By bundling all steps together it decreases flexibility. I tend to prefer more flexible code, perhaps to a fault. it also make debugging more difficult, wich is something to watch out for when using these functions in the future. This way is simpler though. 👍

**Comment by nhew1994** [comment]
So what do you propose then?

**Comment by lukeamyers** [comment]
I propose we keep this. I think right now what we aim to produce is a dataframe for each calculation step for the system and we should continue with this the time being. I think in the future we can incorporate a `System` class `Configuration` class and `Calculation` class. This will introduce hierarchy of the steps involved. For now lets continue with the flat process of each step for the system. Let me know if you want to discuss, but these are future thoughts.

**Comment by nhew1994** [comment]
Sure. If you can come up with a rough workflow/diagram that would be easier to visualize.

**Pull request merged**
