### PR TITLE
Mag_data update + plot_mv() bug fix. + plot_config_energy() update

### PR DESCRIPTION
**Pull request by lukeamyers**
### determine_magnetic_ordering()

- decoupled this from extract_configuration_data()
- Introduced magmom_tolerance and total_magmom_tolerance for determining the magnetic ordering. The default values are  1e-12 just to avoid floating point errors.

### extract_mag_data() bug fix

- previously only worked if the outcar magnetization (x) data had headers "# of ion", "s", "p", "d", "tot". Now works for any combination of headers. e.g. "# of ion", "s", "p", "d",  "f", "tot"

### plot_mv()

- updated to work with the outputs from extract_configuration_data(). I don't think it ever got updated it, after removing extract_config_data().

### CODE REVIEW

**Comment by lukeamyers** [comment]
Changes to ~~plot_mv()~~ plot_config_energy, now an inset of the lowest energy configurations is shown.
image

**Comment by lukeamyers** [comment]
Updated styling to match plot_ev()
image

**Comment by nhew1994** [comment]
Why is it called plot_mv?

**Comment by lukeamyers** [comment]
Magnetic moment (m)vs volume (v). A name change would be good. Especially since I do t like using m for magnetic moment. Mu is better. Plot_muv() seems no good though. Plot_config_energy could use a name change aswell

**Comment by nhew1994** [comment]
The plots above are form plot_config_energy or plot_mv?

**Comment by lukeamyers** [comment]
oops. Yeah, plots above are plot_config_energy().

plot_mv() looks about as it did before:
image

**Review by nhew1994 — APPROVED** [review]

**Pull request merged**
