### PR TITLE
Phonon workflow

### PR DESCRIPTION
**Pull request by nhew1994**
First attempt at a phonon workflow. Added:
def run_phonons
def phonons_parallel

Also modified a few comments in workflows.py

### CODE REVIEW

**Comment by nhew1994** [comment]
Added another commit that gives you the option to override the default settings in three_step_relaxation and ev_curve_series.

**Comment by lukeamyers** [comment]
I noticed you change this: 

`sys.path.append('/storage/home/lam7027/work/bin/vasp-job-automation')
import src.workflows as workflows
#sys.path.append('/storage/home/lam7027/work/bin/vasp-job-automation')
import workflows as workflows`

Did it not work with the folder directed to vasp-job-automation and importing src.workflows?

**Comment by nhew1994** [comment]
Oh it doesn't really matter. It was because I was testing the workflows.py in the same directory. Eventually we want to do pip install e . so we can just import.

**Comment by lukeamyers** [comment]
> Oh it doesn't really matter. It was because I was testing the workflows.py in the same directory. Eventually we want to do pip install e . so we can just import.

Cool. I agree

**Pull request merged**
