### PR TITLE
magnetic data update

### PR DESCRIPTION
**Pull request by lukeamyers**
- **update to extract_configuration_data**

  - When collect_mag_data = True, includes additional columns for 'total_magnetic_moment' of the cell and 'afm'.

- **removed optional parameter ion_list**
deleted all appearances of ion_list from workflows.py. It now always collects data for all ions.

- **workflows.recursive_extract_configuration_data**: convenience function for iterating through a list of config_dirs

  `dfr = workflows.recursive_extract_configuration_data(config_dirs, outcar_name='OUTCAR.3static', oszicar_name='OSZICAR.3static', contcar_name='CONTCAR.3static', collect_mag_data=True)
  print(dfr.drop(columns='mag_data'))`
  
  ```
          volume config     energy  number_of_atoms  total_magnetic_moment   afm
  0   355.714286    23c -230.86150               16                    0.0  True
  1   348.571429    23c -230.91777               16                    0.0  True
  2   320.000000    23c -230.99078               16                    0.0  True
  3   312.857143    23c -230.94975               16                    0.0  True
```

### CODE REVIEW

**Comment by nhew1994** [comment]
That's good, but I think we should have a more general column called ordering, and the code should somehow be able to decide based on the total magnetic moments and individual magnetic moments if the ordering is:

- Ferromagnetic - non-zero tot mag and same sign for all individual magnetic moments
- AFM - zero tot mag and the same number of negative and positive individual magnetic moments
- Spin flipping configuration - non-zero tot mag and uneven positive and negative individual magnetic moments 
- Ferrimagnetic - non-zero tot mag, the same number of negative and positive individual magnetic moments but different magnitude

I think that should be it?

**Comment by lukeamyers** [comment]
Good idea. Will do

**Comment by lukeamyers** [comment]
Nonmagnetic aswell

**Comment by lukeamyers** [comment]
The new column for magnetic_ordering looks like this. values can be 'ferrimagnetic', 'antiferromagnetic', 'ferromagnetic', 'nonmagnetic', and 'spin-flipping'
```
    total_magnetic_moment  magnetic_ordering  
0                    -1.0      ferrimagnetic  
1                     0.0  antiferromagnetic  
2                     0.0  antiferromagnetic  
3                     0.0  antiferromagnetic  
4                     0.0  antiferromagnetic  
5                     0.0  antiferromagnetic  
...
11                    0.0  antiferromagnetic  
12                    0.0  antiferromagnetic  
13                    0.0  antiferromagnetic  
14                    0.0  antiferromagnetic 
```

**Comment by nhew1994** [comment]
What do you think of abbreviations:
ferrimagnetic - FiM
antiferromagnetic - AFM
ferromagnetic - FM
nonmagnetic - NM
spin-flipping - SF

**Comment by lukeamyers** [comment]
I like those

**Review by nhew1994 — APPROVED** [review]

**Pull request merged**
