### PR TITLE
Dev/nigelhew

### PR DESCRIPTION
**Pull request by nhew1994**
Update dfttk/eos_fit.py

- Added back the reference config to the plot in def plot_energy_difference
 newplot
- Modified def fit_to_all_eos to give a dataframe containing the EOS parameters
Screenshot 2024-05-11 182258
- Simplified the eos_functions a bit. E.g. - got rid of eos_index which is no longer used.

### CODE REVIEW

**Review by lukeamyers — COMMENTED** [review]
I thought it was better without it, but I suppose it does make explicit which configuration is the reference.

**Comment by lukeamyers** [comment]
> Update dfttk/eos_fit.py
> 
>     * Added back the reference config to the plot in def plot_energy_difference

I thought it was better without it. Although it does make it explicit which is the reference configuration.

**Review by lukeamyers — APPROVED** [review]
Excellent

**Comment by nhew1994** [comment]
The reason I added it back is so the colors are the same as the EV curves.

**Pull request merged**
