### PR TITLE
Dev/magnetism

### PR DESCRIPTION
**Pull request by lukeamyers**
prep_for_vasp.py incorporated into magnetism.py

- generate_magnetic_configs: generates magnetic configurations using newgenstrYW within ATAT.
- essentially moved the functionality of prep for vasp into magnetism.
- some functions are likely redundant.
- some functions might be kept but moved to another location.
- mostly what they do is support generate_magnetic_configs

Workflows

- `phonons_parallel()` attempts to get a magnetic structure before generating the supercell for the phonon calculations. If it can, it will correct the magmom values in the incar according to the supercell. If an exception occurs it will run as before.

### CODE REVIEW

**Comment by nhew1994** [comment]
I really think all the ATAT stuff should go into a separate branch, not the main one. 

Why are there two magnetism pull requests now?

**Comment by lukeamyers** [comment]
removed the other pull request. I'll see if I can separate some of the magnetism stuff from ATAT, so that the ATAT stuff can be in a separate branch.

**Comment by nhew1994** [comment]
What is the update on this?

**Comment by lukeamyers** [comment]
> What is the update on this?

I'm going to try to separate the ATAT stuff and the basic magnetism stuff today. Then I can leave the ATAT stuff in another branch.

**Comment by nhew1994** [comment]
> > What is the update on this?
> 
> I'm going to try to separate the ATAT stuff and the basic magnetism stuff today. Then I can leave the ATAT stuff in another branch.

Thanks. If I have time today, I'm going to try the new ATAT script.

**Comment by lukeamyers** [comment]
I removed stuff related to ATAT, and now it contains only the functions related to magnetism.

**Review by nhew1994 — COMMENTED** [review]
Ok, merge if you are ready.

**Review by nhew1994 — APPROVED** [review]

**Pull request merged**
