### PR TITLE
Dev/luke

### PR DESCRIPTION
**Pull request by lukeamyers**
# Improved plot_ev() function.
- can optionally plot fitted equations of state (any, 'all', or None)
- can handle dataframe inputs with one or many configs
- looks kinda ugly still.
- example use found in plot_multiple_ev_curves.py (comments may not be the best atm)

### CODE REVIEW

**Comment by nhew1994** [comment]
I prefer to keep the eos_fit outside custodian. I'm thinking of removing it here and making another repository called PyZentropy.

**Comment by nhew1994** [comment]
Can you import it and use it for your postprocessing?

**Review by nhew1994 — CHANGES_REQUESTED** [review]
Can you make changes to the eos fitting in the eos_fit.py? I think cstdn.py should just be used for sending jobs and extracting data.

**Comment by lukeamyers** [comment]
# Changes
1. moved eos fitting and plotting functions to eos_fit.py and out of cstdn. 
2. plot_ev() is functional and supports str_ files and df inputs
3. option for plotting the minimum of the fitting
4. option to fit data with eos any, 'all', or None
5. new eos_fit.select_data(df, selection_dict) function

# Future improvements
1. improve legend for plot_ev()
2. choose better markers/colors/dashed lines for each trace
3. include plot_pv()
4. add extract_number_of_atoms() function
5. include option in plot_ev() for total or per atom energy/volume
6. separate magnetic and data into separate dataframe
7. remove lines from plot_mv() (only plot the points)

**Review by nhew1994 — APPROVED** [review]

**Pull request merged**
